version: 2
dependencies:
  pre:
    - sudo apt-get install sshpass rsync


jobs:
  build:
    docker:
      - image: circleci/python:2.7-jessie-browsers
    steps:
      - checkout
      - run: echo "hello world"
      - run: sshpass -p "$DIGITALOCEAN" rsync -avz ./srt-resume.html $DIGITALOCEAN_IP:/root/srt/
