version: 2

jobs:
  build:
    docker:
      - image: circleci/python:2.7-jessie-browsers
    steps:
      - checkout
      - run: echo "hello world"
      - run: apt-get -y install sshpass rsync
      - run: sshpass -p "$DIGITALOCEAN" rsync -avz ./srt-resume.html $DIGITALOCEAN_IP:/root/srt/
